apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.enc.yaml
  - cert-issuer.yaml
  - wildcard-tls_arr-stack.yaml
  - wildcard-tls_media.yaml
  - wildcard-tls_utils.yaml