apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:ekpOFFXsA4UiQsMoahueG3e/oHsPrML6v8OhHdzmvzfvnDlkUf0ykeSHt6WVFTvIkX4E4/U=,iv:2EEsSZW4vD4sUU8cB74qY+sEbplsZEcev0pFE1X6e5Y=,tag:Ol1eB9435H5tDz8zpCLwLA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbmxhSllVdnhpVGdpb0xC
            RWN0OWNvOHFhVUxPMnhKcGJDQlQ1WWJXblJVCmsyWWgrUzY2YVZYOFExT2dOMkdl
            UTR1anVuSDJYMmtrT1lVUUtBdFFsY3MKLS0tIENxbnJRakx2YmVoSHUxUWl5d1Zn
            bytYeG5nU25Bc0R1WElyNmtmaW83bWcK9U0D5yFs3cyyHBtReoVto0E74lwbBRao
            3ZKA6LLAPMs3kiHlkB3QsEha9f3cszfF4oz6aZiORtBD6yo/vhXCFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T01:42:52Z"
    mac: ENC[AES256_GCM,data:KCoyg2L/9LWTln4UkZVXCTruTBOTQqgHK1HAsCMAZh8t9r1ltiOB2asay1LScoNfxiFGcCHV/ieIgDcPYezWFEDBB2GMzYaZThvIkM8vG3QqAch56xGdKdIWFhz69VETU1T6C7b/bOMLz4Og7CFasrP/Xozq1/6To/MLlNRgCiM=,iv:qL+u4Af2pq5Gch21K6fRGiXhUI8/FkKreFL9nMs/614=,tag:6BUGrpGc8cT1a/v/i4FXkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
