apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: immich-data
spec:
  storageClassName: ""
  volumeName: immich-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi