apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: immich
type: Opaque
data:
  # Encrypt these with SOPS - replace with your actual values
  DB_PASSWORD: <encrypted-postgres-password>
  DB_USERNAME: <encrypted-postgres-username>
  DB_DATABASE_NAME: <encrypted-database-name>
  JWT_SECRET: <encrypted-jwt-secret>