apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
data:
    DB_PASSWORD: ENC[AES256_GCM,data:NgPoQOtsrcGBtU1N,iv:V9yW7RQLmvSDJlDIwJrbWt63eE4+jvZ7SFBW4FH4CfY=,tag:NyvOF+8YNFumhh9A+caq8A==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:TesyOMc7,iv:Jr6KdUks1RHgQsov3mvhxW9pRTBHWhbODR7QXORrl/U=,tag:DuOjFTevMgub0SciTip16w==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:mdWEH5dZ,iv:j6w9X5io4Clyvce/nHw5eDgH8Plqy+irVhGanUYijMg=,tag:pu/TyHpIcylgSTkZ9yHgRQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Qh2YFRFxQygs93mz9otLjaQWUuD6zw==,iv:aA+uTbyr7fDwJODGnedFbeSCoX1RI5ooz96jbhb5Dpk=,tag:GyIIy/3qbpCli4y6R7MUpw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSEtpckVjMjRJRWJzZHZ4
            SFVocm5KUUt3ckdZRlMxd0lOSW1ZUEhEaXpNCmRTelNnaWRHeW9la0RDQTBYeTBz
            UHVGRHFGNm4wajJhcEJhblMxSFh5QUUKLS0tIGdXeTBRaXllYkU4YWlhSWJrMmVZ
            dVVHUkNGZWh0Y285MXp6TVIvNzFkNHcKEv9RadzYhjGcQimMLAItVSKN+OfYsHBM
            vvNGcI9XE7YrXHuBWuhQ9H7725xtxHWMlZSYGJ3za0qxz+JNj0iR2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T00:57:36Z"
    mac: ENC[AES256_GCM,data:m+yyzd4SQyTd6c55MV+GvYsungeLB75SeDrM8OJfxOsh/qhHcHTUOzVHs0jCx8YPMXXp3SyqCxMb+8OBJu27pgflv0OD8NiaAuPNs79t21A7bXML4RqselMU92cktyRh80xhLyR7GCUjogdlHArwTMoB3l0eqFB8uAL6zEph1P8=,iv:zBRksLh21LOIlhV2909uhvxEYfDHcfly6NGJ+i/rbhk=,tag:L2DWM5IskDetlOERQ3UzzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
