apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: utils

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mealie

  template:
    metadata:
      labels:
        app: mealie

    spec:
      securityContext:
        fsGroup: 1000

      containers:
        - name: mealie

          image: ghcr.io/mealie-recipes/mealie:v3.19.2

          ports:
            - containerPort: 9000
              name: http

          env:
            - name: PUID
              value: "1000"

            - name: PGID
              value: "1000"

            - name: TZ
              value: "America/Denver"

            - name: BASE_URL
              value: "https://mealie.alarlab.dev"

            - name: DB_ENGINE
              value: "postgres"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_SERVER
              value: "postgres-lb.cnpg-system.svc.cluster.local"

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_DB
              value: "mealie"

            - name: SMTP_HOST
              value: "smtp.gmail.com"

            - name: SMTP_PORT
              value: "587"

            - name: SMTP_FROM_NAME
              value: "Mealie Recipe Manager"

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: SMTP_USER

            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: SMTP_PASSWORD

            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: SMTP_USER

          volumeMounts:
            - name: config-volume
              mountPath: /app/data

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            httpGet:
              path: /
              port: 9000
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: mealie-config-pvc