apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: utils
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:et5BMQ4i,iv:Vff2+I6PajCnrvgWzke3ktTgFEQavP3Jq/2C5NouZ8s=,tag:sbvXzpS3cNUCh5XAutasyQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:X+EmexuS9rOdxXqY,iv:gpfZTMLzzC7Eex9Ym9IGM3np7OIFYw+orbnlgFZ6BOI=,tag:kKuAFd8ttD6HrQKAoD9xGA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:krju/wViu1gL/1axMPyydlCl,iv:DxiYTTEdDVVZSpe8hcI+OrVza7tq7eVR1m9fbJBD7lk=,tag:WVk7QN4EwPpL3mVXHzmxdg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0OUtGkAHMP8D18caGvc5CLvtJA==,iv:L3viZ2HyzF/f0WLoCvmuc42+EVMXsD7jdQsQt3BmOIQ=,tag:b9g9oXuJCN2soThFByPdvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ1FuZlFxTlFjZXYwNk5U
            R05jcGJUNzZmejUzZDhtZm8yN201SmV0QlRJCkVWM2VRd3ZjaUFHNklEY3hhQXpv
            VlJBV3dOUzI0SW5kbWFEaE43bDVUUDAKLS0tIExGb2orcUlma25DaURFTE5EZ2t4
            WFVtc0FHbGEzVTBsZUFmWU5oeWdPMjAKDRIpbAkwqrpFU51wK8jjQvQEQSq3ULz4
            nuMs4unZOqfLYz3NcoGypBOkHsrdk5v/jkzUULZxkk+12aA+dpl4Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:43:06Z"
    mac: ENC[AES256_GCM,data:5bLVLiK6LdbPRGfzr0XTWFQOvcVTzNQ9lQCYozMq7OIqvki4nEMi0CrkLsfFZ2Ffrsy181b/n6aCCdLe30UtVomwc103tZS0tq2fjQtsvGBmVUo8xPnxTNVQxSaFFqMhmzXL0RqNvuhnXr6vL/vXwUKvVOSamWxpnE92PnxfRwo=,iv:/kA5yR3saLyYHaNJQRK4s1VsycQWjmGEF/tTRdCnfa8=,tag:fHqGSL64Jho7RHYK83Nzyg==,type:str]
    version: 3.13.3
