apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-media
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: home-infra-post
    - name: home-database-post
  path: ./kubernetes/clusters/home/media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
