apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---

apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---

apiVersion: v1
kind: Namespace
metadata:
  name: utils

  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io.audit: privileged
    pod-security.kubernetes.io.warn: privileged
---

apiVersion: v1
kind: Namespace
metadata:
  name: arr-stack
--- 

apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---

apiVersion: v1
kind: Namespace
metadata:
  name: database
--- 

apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager