apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/audiobookshelf
    server: 10.0.0.79
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-media-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/audiobooks
    server: 10.0.0.79
  mountOptions:
    - nfsvers=4.1
    - noatime