apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: audiobookshelf-config-pv
  storageClassName: "" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: audiobookshelf-media-pv
  storageClassName: ""