apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-work-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/adguard/work
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-conf-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/adguard/conf
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime