apiVersion: v1
kind: Service
metadata:
  name: adguard-ui
  namespace: adguard
spec:
  selector:
    app: adguard
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: dns-setup
    port: 3000
    targetPort: 3000
  type: ClusterIP