apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolver
  namespace: utils
  labels:
    app: flaresolver

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flaresolver

  template:
    metadata:
      labels:
        app: flaresolver

    spec:
      containers:
        - name: flaresolver
          image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8191

          env:
            - name: PUID
              value: "1000"

            - name: PGID
              value: "1000"

            - name: TZ
              value: "America/Denver"

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 1Gi

          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3