apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: plex-config-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-tv-pvc
  namespace: media

spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: plex-media-tv-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies-pvc
  namespace: media

spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: plex-media-movies-pv
  resources:
    requests:
      storage: 10Gi