apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
namespace: metallb-system
resources:
  - github.com/metallb/metallb//config/native?ref=v0.15.2
  - address-pool.yaml
  - l2advertisement.yaml