apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diyhue-config-pvc
  namespace: diyhue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: diyhue-config-pv
  storageClassName: ""
