apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m

  sourceRef:
    kind: GitRepository
    name: flux-system

  git:
    checkout:
      ref:
        branch: main

    commit:
      author:
        name: flux
        email: flux@users.noreply.github.com

      messageTemplate: |
        Update container images

    push:
      branch: flux-image-updates

  update:
    path: ./kubernetes/clusters/home/4-apps
    strategy: Setters