apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: overseerr
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      containers:
      - name: overseerr
        image: lscr.io/linuxserver/overseerr:latest
        ports:
        - containerPort: 5055
          name: webui
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Denver"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: overseerr-config-pvc
      - name: overseerr-downloads
        persistentVolumeClaim:
            claimName: overseerr-downloads-pvc