apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/apps/overseerr
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-downloads-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    path: /mnt/apps/qbittorrent/downloads
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime