apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  namespace: overseerr
spec:
  selector:
    app: overseerr
  ports:
    - name: webui
      port: 5055
      targetPort: 5055
  type: ClusterIP