apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-config-pv
  namespace: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/wireguard
    server: 192.168.0.26
