apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config-pvc
  namespace: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: wireguard-config-pv
  resources:
    requests:
      storage: 1Gi