apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
  namespace: wireguard
spec:
  selector:
    app: wireguard
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820
      hostport: 51820
      nodePort: 31820
  type: NodePort