apiVersion: v1
kind: Service
metadata:
  name: ddns-updater-service
  namespace: ddns-updater
spec:
  selector:
    app: ddns-updater
  ports:
  - name: webui
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP