apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: infra
type: Opaque
stringData:
    config.json: |-
        {
            "settings": [
              {
                "provider": "cloudflare",
                "zone_identifier": "c0b3a219e1406ea23740e25c8b254991",
                "domain": "alarlab.dev",
                "token": "GGi3EUs68Y_DIk5rct6yO08EHbQ2EFMesnJYC5rk",
                "ttl": 600,
                "proxied": true,
                "ip_version": "ipv4"
              },
              {
                "provider": "cloudflare",
                "zone_identifier": "b313f9dcc59f96b481ff61a2e6e43ac5",
                "domain": "packetsandpods.com",
                "token": "GGi3EUs68Y_DIk5rct6yO08EHbQ2EFMesnJYC5rk",
                "ttl": 600,
                "proxied": true,
                "ip_version": "ipv4"
              }
            ]
        }
