apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: infra
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:tafyC0naqk5s/F3yjQ6tTNne2p0YttPebGufiEydv8KihhkarLNdlHm453RP3hMjEHh/aeBcKa7EmZNKSxTshhMp665ceo9pYfCElW1TTxzcC/Hm9Tzk2oNU2UmETUUAmer+DbtARC0lEwczq59hzj7PaPhg2nbsqiCvcoBj/UGFgDRIY96EpqwHFLgZPsSpkqxQWKCU8QBP5wIp7DQ6YREU0+f4e22iio5Vng62XhBB/K7gNwLuFzNOTAOvsY9XuZLDb8o2JoIoXjxZub15NHJgmDYrKii+6ne3Nv/oZQ5Q+srAmcXHXwtDnI4g8dFzGDmTOT0kd7Bxim/G8qFqh+pcYIdeRLfoZGhV4q91Lbk3cP0FpMW9A00O3TZ7AH4YEHsR3QxbQDb7DBCYudWZiqm4JK3zXHmaFyoj7ZTLKAE4CFmI7xknajLy8zeMwvICAC/kJy8MlMwshUhR4hXr/LBZe3FgqcNSP01UKv4I6ZWXLzk4SR9zAEput9VmPdzsRpy76Tn1V7XKPwfrEofJ8XoeD0Lygbq/MpdpOe53tPuUNEmIprS2afoflYKyV7K/9tEyhNXrL4ysjIbBi/peDVh+SbXFiKGYczYl4QtdY+sFvahtzPYlCKtRQjdBkfbovWdGYGIX+cF6TD5+Cr9pxvbNGdgOZeEPfVBTo8qLhmC7J1tMXNO63st/bNWV4pLz0levxuoloTj1q5bUCcYk35dhbvc5WGKi+7jLsBsd3E7XKv4DxY1vStftpI5gowU1/Lch7tRf9bDEsNgeUKMZZVDNNWOzos1GRMENkVLS0DOjBjFXpXCISecyweZOnKs=,iv:B29VaBn0IWzAjgvKbSnIpPU4KQrArgyjxdm8+kxMD4I=,tag:Q/DlJkn4EZBSEV9XVx3uJg==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UGFpWEZsSzEwMXM3cFZH
            MThKZEpodFpqZGFQTlpsVThTQjhEY3pjSFZrCmxLaURwSlNrYUdMS0pQVWYybWlR
            WVc4eC9MQU5ZRGNEaDMrNmRFa2QySjAKLS0tIEZVUVJaWE52T1JvQkZUVFAvaXIz
            VTZUYnl2aDdsMzgxNW1QalAwdkl4MGsKetaz9Acq/eIQIxKRBfp94MhxLYKFx8ni
            /htPjdKlfzJd8F9/2PYm2Lfk8ERNSDjls0bY3t7z2ILZ8UZOtjVPGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T02:38:52Z"
    mac: ENC[AES256_GCM,data:Re6vNj1XHAQR3pbrTI8tVDfskJjdo7zjstPAXnRj0fxobZHM8Met8nlCSOaV+pTbEQ4D88/EgrLhXWa5SS9f/41KTd0+ve2cPOe+7aKm4IrpTWAU6MCMBRagk2QR2O7Rrxala/ZwZuRgWcILxrTh2rIdUOKaqmQS03wJmp0ZlLo=,iv:lF71rkmABvIO2dF1Ri/pfI4fGtUj6GiM/I8ocq9WgVI=,tag:PuMkuZE/BBBTqFW9nOaysw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
