apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: infra
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:RgVCuYzYaB5CNgNHCtwHBxw9OCi2n+UY9WH89pXkpVgwV5xIp5cGjnicz8Jib88SSKulcmzmEFjMzcDnPD1M8mNU9pXBrKDo7j7cNdIrkdDALtuObV8W/J/iYBxQbiNIhEWsuMcuB/7EtXBsJ7FiiXPAqz22F5qUhaG8oOzzsUUnLA+XiAPOo2WJHxlhIRaCq8X77YxRPs+c1ZkcHLxXoY0r7StVmUjU1AqfW8KR49cjNAQT5yW4X1gpLFHsTLjZt2rcmQ25UJuhKeH5H+fV7MUY/gcFuFhfYdGLu5kG9MXFKCQEXhJcYIBpAcaTKly2bfKStKbm/28jztJLlIMobqzhivL5d5TFX88v63nH2xro2DHyexxwvGbwxQsA5+FNfeciTyj5tId6jKb4jaA/jd/UB1WMA2/IdT2XeIjYw6m1dZyi/zeEVjIXqWKqQi7YET059t47HESE7ZWMffvf52Ap+CbCSzrpbBiZcx0/BcxWtewZW10tLprsdbBA6EHc4jKgUFIVj9eMpd1c8PJJ57Pj/8+3PUxvhGcdeUZzk4FxFnebNxgNggfvYMr2ICD9Ktuk3l+MDCy/rC6AEsVUX4qP8ttSEzSpm4HESfsh62gJgdBljVryZwdbYPFfm6vrusLAoGISemtCyM0EdPj+qPMy6XemSImlHzPk5esZpQIBEH1GDCIdjqOhsYmijcT7LTHoW1lovE/sLyErzp/U4lATUvM6jIAMLC8SvKDqu2pMcKhBWZebdrXunJ687gbgyRw+JMuyFNrvQOqC2SKgrZQnJbKoZXuhLyUauPHOIsJPUth1+jsMZR8Ss/6vn40=,iv:7cZhu7t1e3NQ5/MOXt2unKyyabcwrz/Dz2OmLm2PY4Q=,tag:io0dVEGYrzl9Jwp0NuDyAA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzekFBYmZRRDhFdGNKTDVI
            UnoxbkpUZjk3ZisxUlROM2x1T3libWlVYzJ3CjFCbE5VeElYWTBNVExCWGZUZzFk
            WDRJUkMwYXhGdFRIUHgrVXpYWkhDdVkKLS0tIHdVVXl5c1pWTXVJUktNSzJMODE5
            NlRuVEVvSVdaT09WczFwTlhVUXo1ejQKnCISVF9PtdpjNs266QZ4kT3IaPZhpwFq
            sOXSntLMz1d/fSEWz3hQS6BNiJhsbbxzILI5X/V+6CE6xHDsqbxEwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T01:34:26Z"
    mac: ENC[AES256_GCM,data:agTkOJ4DorH/wj1PxY4qQQ8wHq8oMWvWLXK6a06ADaNwoigfpFG0jij9mGPfcEvU9lAIqDittikWt0dvUfAqPPbNFpwrlzon4wQnw+YvcwantL5NtXL3aka7IO0bhkz1rtM+cMUF+HxfDdG2iO3kkytFKLR08mB/61fJX163oNA=,iv:SKFG31WWwtu0PYJgZqCETwTPa7It9fsny0IOuZBRnHM=,tag:2zbMyYjGDFnXfX1KTGXpvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
