apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:VGqHErYy,iv:UC5++ruOP6l2OToU9ICPpqyMaVUbIkxPacmOdoLT0dY=,tag:bK0ugbT1Sv3QYCFvt5VYSg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4Ff0S6uRa2R6I5qa,iv:tt9C/vDWGehogoCCYJdsFN5Cklas+nI9Qjhm2kzGaoQ=,tag:tL8VT6sUOXkqKSABtuGcSg==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY2FpRmZIMVljRG43eFN3
            aE9EQTV0Y3AyVGpXWnlZRHJsMWt4WWRGRndvCjFFSWYvQzM4Z3ZrOUdKTmJiNzhD
            bW4reDEySjNEQXgvZ0t6a3RKS0d0NUEKLS0tIDhTTEtVUldXdmRZem1tMVFVTTBE
            UmozUUIvTmxBcS92Zmd6N0pqNUoyN2cKU1Pi6Za9eALpzEFpXiE+coNUhnpLgRM4
            fMIlj1otOv7/A4mMXV4HOtnf02H6Mc6xF+qtsFcIHSCHWEDt6PEngQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:28:52Z"
    mac: ENC[AES256_GCM,data:ShqRUEjdtHV71aTGWPYJ0ybI15xmNdxSYHsDW95tzsrIKmOM/k9JWCZqNLrSoLHMfCz4fN1SDuSAPj+bvANWOj927Hx014e1pvkxgkx7W3DXaZn1Shbu/+pm7wPMuN4PTnubc2doyhDY5jEDUYKpzBZy27SU5xWfRdC3lbMYGmY=,iv:aCL76qnurUHU+cP6qAvK3GrN+O099EQ/1UQE69bVGE0=,tag:o7CcS2bqIXB/o2teVRJFcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
