apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      nodeSelector:
        kubernetes.io/hostname: worker-02
      containers:
        - name: postgres
          image: tensorchord/cloudnative-vectorchord:17
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          ports:
            - containerPort: 5432
          env: 
          - name: PGDATA
            value: /var/lib/postgresql/data      
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "md5"
          - name: POSTGRES_LISTEN_ADDRESSES
            value: "*"
          envFrom:
            - secretRef:
                name: postgres-secret
          args: 
            - "postgres"
            - "-D"
            - "/var/lib/postgresql/data"
            - "-c"
            - "shared_preload_libraries=vchord"
            - "-c"
            - "unix_socket_directories=/var/lib/postgresql/data"
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-data
