apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin/base?ref=v0.36.0

patches:
  - target:
      kind: DaemonSet
      name: intel-gpu-plugin
    path: patch-daemonset.yaml