apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-nfs
spec:
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/media/movies
    server: 192.168.0.26
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-nfs
spec:
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/media/tv
    server: 192.168.0.26
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/apps/plex
    server: 192.168.0.26
