apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-qbittorrent
  namespace: vpn-qbittorrent
  labels:
    app: vpn-qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-qbittorrent
  template:
    metadata:
      labels:
        app: vpn-qbittorrent
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8  
          - 1.1.1.1    
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: SERVER_COUNTRIES
              value: "United States" 
            - name: SERVER_REGIONS
              value: "Colorado"
            - name: SERVER_CITIES
              value: "Denver"
            - name: SERVER_CATEGORIES
              value: "P2P"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secret
                  key: private_key
          ports:
            - containerPort: 8080
              name: qbittorrent-web
            - containerPort: 6881
              protocol: UDP
            - containerPort: 6881
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ping -c 1 www.google.com"
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ping -c 1 www.google.com"
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp/gluetun
              name: gluetun-data
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN           
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          volumeMounts:
            - mountPath: "/config"
              name: qbittorrent-config
            - mountPath: "/downloads"
              name: qbittorrent-downloads
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc
        - name: gluetun-data
          emptyDir: {}