apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /mnt/apps/qbittorrent
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    path: /mnt/apps/qbittorrent/downloads
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime