apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: infra
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:zrWwfa3rVdhIqNUyIl+j9WzsP4KiMXjkpaVLhFMbU0sU1PXajdZnIy7Kn1YSJJHmtLieOng=,iv:z5kPiwyDfV7hsxzLtQns9iW2Bg3gADa0IaSH3FsQbJs=,tag:suwT873aIM1q9lbZ6eAbyw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Qm9uN0Y3OGxaK0xBZmps
            QnlwWDZ5T2pQalpack1kNXEvcEQvbWF3WjE4CnllM2ZPcFl1S21rNFhPbGZCK1la
            ZG5EMHBHWmxTN0pLLzNzS1gyVVlQblUKLS0tIDRpUkVOcnd2bXp5THFBdDFReHdB
            ZWk3NVdCdXdGV1FheWkwTVlMVWJ3SU0Kc+YwFgXvMXZsWMLG11ofvhHkAK0Omlvn
            qUUHf4do8VDhF6VFuKfGr4xhLOIJrESMCxS9oWSDhczCPOvCoWsTZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T01:37:39Z"
    mac: ENC[AES256_GCM,data:qZX8rBBkuobOqlygoQ3kDLi7qlVXL5ceZ8BMSgAYqm5CMoUsCkObUzlUee/FL7z0u41W5IHXDG7qkztTMYjlzk06E6xE+0XEYGe0C/5XvvqI6/EQKGFJiIL7gbk1wLG7uEGVqRHnD3jZYm6d2aNbXHje2Vh6GwOutgJORn1RRSY=,iv:i5f9vk3vvcoUOQ2zjrt3XNgxM3wwhZygD8HFIIMH67I=,tag:C/OFuch34qgnaHh87UMetg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
