apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: infra
type: Opaque
data:
    apiKey: ENC[AES256_GCM,data:RfOL5XEAmjwraLzP1/BlBAP4jta54k8OuB4GklluCrumq+N+sWMLEghDYhLKpFfZwLPShs3Tyew=,iv:bkGZu+8eDFZ7DVVfKSTh3eGkGjluiqILMdJ5gi66Lek=,tag:H7NIZruTN8xVJ/tEr2Hb8A==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R1lmUytzTzEyYVlsNW1u
            OGk2RUJ6Tm5aaGxvUjBSaWFjaUk3U25EZUJvCk8yRzJGdmdTdEFKVzlCM1ZJaE10
            NVNibGFjTUVSOEZnemJJV0tNWk45S1kKLS0tIFl6UmhvbFFmZWRwTGlieFQwdmpW
            N0lMK3YyS2ZUemVDUG5xVzY1QTRlalEKwyjsrRgpoEnjiQXHGec2kUinjjn74ZpB
            HPSF/w/aAUxV2W/49Oqwo0KudN3TirThKeZ5mHl/Mz7BFUns/DuFTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T01:28:44Z"
    mac: ENC[AES256_GCM,data:npblJa140DtPf4K6XTGBhsfOJN1RoKCMXkjRf1Kpb4DfHrEsALpA8AQ/m40JfQduaCAZUNE/UE0JbTd2DTWBT61yZDUaMtSoTcpAIHA/qZNSTDrtDUdzqG2XP5A6Kx9zwKcr4X1AwQCIwTZKn8fIpv0wfelXb8bDsPVj9sJmh1U=,iv:gwV0uYNrWSkr2OyzObYNfYWmBfvEpqyFj+4FTPzOGqU=,tag:HMd4pPnO4UChUGglZurAbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
