apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 13378
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Denver"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: audiobookshelf-data
              mountPath: /audiobooks
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-media-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/audiobookshelf
    server: 192.168.0.26

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-books-pv
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/audiobooks
    server: 192.168.0.26

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Match the PV size

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Match the PV size

---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf-service
  namespace: audiobookshelf
spec:
  selector:
    app: audiobookshelf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 13378
  type: ClusterIP
