apiVersion: v1
kind: Service
metadata:
  name: plex-external
  namespace: plex
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
      nodePort: 32400  # Must be between 30000-32767
  type: NodePort