apiVersion: v1
kind: Secret
metadata:
    name: superuser-secret
    namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6cv2Io6Zilc=,iv:xmCLkhcsGXMixWFRcQlUiaR35P1P/2+TEJxLm8BVLyE=,tag:RXvymrOw+TIg3qmyUnsdhw==,type:str]
    password: ENC[AES256_GCM,data:PYw0Nk+XFlgULtag,iv:WLk1i4NLcK038N9rlOqnxB8n7bpegdxaMJrjUgqPWcU=,tag:OJhmAZ6XWQpL+k06Fqpebw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ekREZ2Z0N3FneW04OW8w
            SFBhRmhiUEJKTEdqaUtKN0FDc0tUbjZaOEhFCi9tRTRPT1B6RUFSUGVrMEo4YmZL
            VlRTOWFyMTNKMS9NeEtGczRvNVV5czAKLS0tIHFHVjk4aWNlY1VaOW1uVWxPUkF5
            elFVdVFTWUZVVEppTktmTDhYT2lyVkEKyF4N3KkzYMAd1In2NbDkevBK8PEr/wm3
            ueSQPJ+0kgDs0kVvBYBuJQwtHtodIEg8dm/aXlbdhaHJVbl6eaKQGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T02:25:45Z"
    mac: ENC[AES256_GCM,data:0mgYTUmM1RCrzZwh6ON50ZEU+o8+1sQXPhZmigao4ntCpKmC0BdiPXfj2MpKT8slNfQfUApNmijtWr3fa5RJcD7SLlQ/EjHY/SSwpPPJgwtddnC+0kmXqwniQtZveblx5t1iq5o7mHuSHZcy25aNfcqgTcdNU0KAqb30YlixHGk=,iv:jK9uVJvcflWCuIbueOMKx/LVd12+8mrik55sumTjIdU=,tag:bO3LwgeeF/0+5nc+6Fy5XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fv72sERYShs=,iv:a+4fCvFfkKhati7C9IwTajq+hwXMpYuuNgjpFsMwo1g=,tag:FTX8HBKEsImzJTW2Tu8m9Q==,type:str]
    password: ENC[AES256_GCM,data:g7yMgqi5nUt6Y7Si,iv:AQsfAzuRzuaXj5BhV2aF35mKwSZZTjgkWsnDCzlGQyw=,tag:5lLWf6u6bX97325Uo4OxQQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ekREZ2Z0N3FneW04OW8w
            SFBhRmhiUEJKTEdqaUtKN0FDc0tUbjZaOEhFCi9tRTRPT1B6RUFSUGVrMEo4YmZL
            VlRTOWFyMTNKMS9NeEtGczRvNVV5czAKLS0tIHFHVjk4aWNlY1VaOW1uVWxPUkF5
            elFVdVFTWUZVVEppTktmTDhYT2lyVkEKyF4N3KkzYMAd1In2NbDkevBK8PEr/wm3
            ueSQPJ+0kgDs0kVvBYBuJQwtHtodIEg8dm/aXlbdhaHJVbl6eaKQGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T02:25:45Z"
    mac: ENC[AES256_GCM,data:0mgYTUmM1RCrzZwh6ON50ZEU+o8+1sQXPhZmigao4ntCpKmC0BdiPXfj2MpKT8slNfQfUApNmijtWr3fa5RJcD7SLlQ/EjHY/SSwpPPJgwtddnC+0kmXqwniQtZveblx5t1iq5o7mHuSHZcy25aNfcqgTcdNU0KAqb30YlixHGk=,iv:jK9uVJvcflWCuIbueOMKx/LVd12+8mrik55sumTjIdU=,tag:bO3LwgeeF/0+5nc+6Fy5XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: cnpg-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:m5668j4J,iv:EuSMSCmeIbz9FVgUG21dqOpijyenx2JDx1ThTSCzwuE=,tag:+td4+Lcy0u3s29xu5KI6CA==,type:str]
    password: ENC[AES256_GCM,data:QxCPfxJlH0M9R8o1,iv:9+g/d8hrtbrQMRPFZfW2x2fGElzpnwRCccF9XKTE1Ms=,tag:HY+wiN3JChwirK8xDNHeTw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ekREZ2Z0N3FneW04OW8w
            SFBhRmhiUEJKTEdqaUtKN0FDc0tUbjZaOEhFCi9tRTRPT1B6RUFSUGVrMEo4YmZL
            VlRTOWFyMTNKMS9NeEtGczRvNVV5czAKLS0tIHFHVjk4aWNlY1VaOW1uVWxPUkF5
            elFVdVFTWUZVVEppTktmTDhYT2lyVkEKyF4N3KkzYMAd1In2NbDkevBK8PEr/wm3
            ueSQPJ+0kgDs0kVvBYBuJQwtHtodIEg8dm/aXlbdhaHJVbl6eaKQGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T02:25:45Z"
    mac: ENC[AES256_GCM,data:0mgYTUmM1RCrzZwh6ON50ZEU+o8+1sQXPhZmigao4ntCpKmC0BdiPXfj2MpKT8slNfQfUApNmijtWr3fa5RJcD7SLlQ/EjHY/SSwpPPJgwtddnC+0kmXqwniQtZveblx5t1iq5o7mHuSHZcy25aNfcqgTcdNU0KAqb30YlixHGk=,iv:jK9uVJvcflWCuIbueOMKx/LVd12+8mrik55sumTjIdU=,tag:bO3LwgeeF/0+5nc+6Fy5XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
