apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: database
spec:
  serviceName: redis
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: redis
          image: redis:8.2

          args:
            - redis-server
            - --appendonly
            - "yes"

          ports:
            - containerPort: 6379

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000

          volumeMounts:
            - name: redis-pv
              mountPath: /data

          startupProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 10
            failureThreshold: 30

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 20

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-data