apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/sonarr
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/media/tv
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/qbittorrent/downloads
    server: 192.168.1.13
  mountOptions:
    - nfsvers=4.1
    - noatime