apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-easy
  namespace: wireguard-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-easy
  template:
    metadata:
      labels:
        app: wireguard-easy
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      containers:
      - image: ghcr.io/wg-easy/wg-easy:latest
        name: wireguard-easy
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        ports:
        - containerPort: 51820
          protocol: UDP
        - containerPort: 51821
          protocol: TCP
        envFrom:
        - configMapRef:
            name: wireguard-config
        volumeMounts:
        - name: wireguard-config
          mountPath: /etc/wireguard
      volumes:
      - name: wireguard-config
        persistentVolumeClaim:
          claimName: wireguard-easy-pvc
