apiVersion: v1
kind: PersistentVolume
metadata:
  name: wg-easy-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/apps/wireguard-easy
    server: 192.168.0.26  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - noatime