apiVersion: v1
kind: Service
metadata:
  name: wireguard-easy-ui
  namespace: wireguard-easy
spec:
  selector:
    app: wireguard-easy
  ports:
    - name: web
      port: 51821
      targetPort: 51821
      protocol: TCP
  type: ClusterIP