apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/apps/postgres
    server: 192.168.1.13 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""