apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/apps/postgres
    server: 192.168.0.26  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""