apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config-pvc
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mealie-config-pv
  storageClassName: ""