apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: infra
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:tpzFnRsdQO/hHie6gb2lXbRF7GZo6Xt5jmoIcvDitMQyHgg4N//6RMa5WH2u3Kz3EoqiNDA=,iv:Q+QEt/+SmfMtwdIt45TEtZv5NihLgIfGFPFwjFY61+U=,tag:6i4j1Wo82ua+qjdmjcH9kQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYjNmSkpTQ3dWcks1Tk5u
            aEVRR015Yytxb2ErSFNsRWRqeEkzMWI4WXd3ClhESFpxZ2NkU1lEN042M0RFT2FI
            MEl1Y2JmS0lSRlRhclV3N1FjOUx2b1UKLS0tIDRabkxjNWlDb0g2ZVlxRUJxN243
            bGZTM2hEcUV2SEptdk9FSEFXQngzME0KwZhWi/XfEIkukiwCEpeJOHPniwY22kiO
            pL/GafwuxRa4Q2Qjc9eWV5Qp8ZPAsKi5WNeFqKgjvGFtItd5HPDIeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T03:28:17Z"
    mac: ENC[AES256_GCM,data:kVF+2eLefs4ORSGKEiawtCQLaLrBmHBlVKnhz6GmCyfojZ8N/2B30ULmLG6D9vyBu+q7vquP4AhRCW0+wEnJHBmcj9jyoSc7Ot5sZH5EV2j7ussHwj1xQe5LycwLPbtQ5bhyYfUjAz8ZHhG7M6OjPaogiochtBqjkZs3VW3Bs9s=,iv:SoaIkd/DeuGYSnwuHMpOe0bRlh0vgp90nM4O991X/UA=,tag:IJnxdhwVSBzilOBhCRgt7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
