apiVersion: v1
kind: Service
metadata:
  name: fivefilters-rss-service
  namespace: fivefilters-rss
spec:
  selector:
    app: fivefilters-rss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP