apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-01
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          ports:
            - containerPort: 32400
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Denver"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-claim-secret
                  key: PlexClaimToken
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: INTEL_OPENCL_TMP 
              value: "/tmp"
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /media/tv
              name: media-tv-volume
            - mountPath: /media/movies
              name: media-movies-volume
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeDevices:
            - name: dri-devices
              devicePath: /dev/dri
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: media-tv-volume
          persistentVolumeClaim:
            claimName: plex-media-tv-pvc
        - name: media-movies-volume
          persistentVolumeClaim:
            claimName: plex-media-movies-pvc
        - name: dri-devices
          hostPath:
            path: /dev/dri