apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-01
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          ports:
            - containerPort: 32400
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Denver"
            # - name: PLEX_CLAIM
            #   valueFrom:
            #     secretKeyRef:
            #       name: plex-claim-secret
            #       key: PlexClaimToken
            - name: INTEL_OPENCL_TMP 
              value: "/tmp"
            - name: HARDWARE_ACCELERATION
              value: "1"
            - name: VA_DRIVER_NAME
              value: "iHD" 
            - name: INTEL_GPU_AUTODETECT 
              value: "1"
          # resources:
          #   requests:
          #     gpu.intel.com/i915: 1
          #   limits:
          #     gpu.intel.com/i915: 1
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /media/tv
              name: media-tv-volume
            - mountPath: /media/movies
              name: media-movies-volume
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: media-tv-volume
          persistentVolumeClaim:
            claimName: plex-media-tv-pvc
        - name: media-movies-volume
          persistentVolumeClaim:
            claimName: plex-media-movies-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/plex
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-tv-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/tv
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-movies-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/movies
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plex-config-pv
  storageClassName: "" 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-tv-pvc
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-media-tv-pv
  storageClassName: "" 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies-pvc
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-media-movies-pv
  storageClassName: "" 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
      nodePort: 32400
  type: NodePort
