apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/plex
    server: 192.168.0.26

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-tv-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/tv
    server: 192.168.0.26

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-movies-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/movies
    server: 192.168.0.26