apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/plex
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-tv-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/tv
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-movies-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/movies
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime