apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plex-config-pv
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-tv-pvc
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-media-tv-pv
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies-pvc
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-media-movies-pv
  resources:
    requests:
      storage: 10Gi
