apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plex-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-tv-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-media-tv-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-media-movies-pv