apiVersion: v1
kind: Service
metadata:
  name: plex-service
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
      nodePort: 32400
  type: NodePort