apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: utils
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:+CIPaKsN,iv:vlX9RGKx9ZGsJyh7QwYUOv5mj8V+//MxLL7ha74Rl0A=,tag:gKs7oWLkAb1+blfU1uAK2g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oTd4NnlfrbEU570W,iv:dE+YHwvXhTrDbVPxkapx/SrNjmN0yELelcopngV+k4g=,tag:Dtmc22SYVNDYXdL+J7OCtg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:87Ij1X6kravcKgssKCT57ZX/,iv:P4aKMnx7jlSdJEqQdbi8VAbhH+4IsQCso6MVnE7Ab2I=,tag:lvTvzO7ch6bXCu7oq7EakA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:6WCS7YRLZGOli8qyd1Iu39oKoA==,iv:r00aQfeIj3rzxHsgjfV7jxTddLVn63SaaG77s0Vnnlc=,tag:NfqfR2DWb0PPEhhT/4rMxA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2xFSjg3SWwzMnVJZ0Fy
            WXovSmNOcVZBTkNtMU16blVIMkRXRXNybVFBCkl0UC9QRU1tTXpMdXlXNnNtYnY2
            NUh5aXVmd0REaE5Oa3MyblhSU2tYYTQKLS0tIEdXYmc0VWE3RTlNa3NpZlBtclJB
            dWdhR2cyeFV3aWhvM2NvNUJNVkIvODgKT8s/kGXTPLeA5oKcu/QoKFS2OEMGpNRr
            25iHR1HcbVR0rDsk0aVkZ2sdRFwQcs8LaR22jysZ/JoO39awC4OmPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T03:29:50Z"
    mac: ENC[AES256_GCM,data:RImOZLIqBVUWBifJCHnsv5+Oddnvxvug9TCjgDFERH7PWOFyOoijrT1bBZLTISv7EisVQW2t6ADvkm4Lr59ouHzZl0Uj7NXQmn36qLToKTyFNud4aYmcVZAzkxnntM423M71HPrhxEqgYp49N7qDC7vmhq0dV+fxS1mNp/0wou0=,iv:nHpDYQ9Jnejck7WcbUkaxiIZpcFg4gaardU2bV1h1pg=,tag:XjxmHU68Wm0NnUFpoERu+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
