apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: utils
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:RoHYGMHz,iv:JyMA7QZUb0pwOuFNpC5OI82RELe6rmsUENCANdIpXIo=,tag:Bz99hPqUTXk5cNPosszUtQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lSVlMALP3I3sqEuM,iv:CZ0a0eMoUTWQzHf9iQukwjh6FNr+gzrZIzcreh61mxc=,tag:vdNInaZIT3P3YVxUJO1VKg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:6dyDw0dfeT8HMObLlzIkI7Yf,iv:y/HMI7UfdBHsfYSECnngO87vwEh1Y94VXLWJgvzPz6Q=,tag:nuoeCSnBIk7YT2jROHj1cg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:uivyaJjXQnkq/k+QhWgL23shug==,iv:ZXnNOSEz0zkCosVyS8mlmbBnrxy5JcyTil9cv27ZBWA=,tag:QG6p6lsaD0QDFp8WANPYVw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSmJWZWplOGlDRW8yUC9R
            Z2JSam9NL20vNnc5YmN3Y1FpK2g1YTA5d3cwCjdFSUtpdy91M20yL2RWUCtLNW4z
            UTJMRU5DNHpvYkNmbEpSWXhRTHF5SUUKLS0tIHVWWjdWTkxwVk8rZVNvSU85cUxN
            Z0N4Q0lyUG9oVzZ6bnVadnlpZmh5eDQK/Oi/m6N5N/ylrpfzoy89LIdaWWaH+yTH
            tzj5CZtbb/sfRqGaG/Lc8c7osr681wnM9r8tyoYjFVDye7mYXnxNtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T15:37:08Z"
    mac: ENC[AES256_GCM,data:aVuuTPchr4k+C96aAl7HllixP8bHWgccb4VF5tvxOar53qOXwqijcuReiMW+YPMON0zhOOuIDEtNbb5Iz+9Wm5jrR9mAbRkedZw8OzaE3FUJE+TF3FnIcF5hQlMR6P9knqwhzR/XGAvo/sfAg5nf+QGoHQhXHK0tp5uCyPuHs9M=,iv:ob10MjdTmYHl+1Ki/2ew0pKXcFyxjOCBmtUz3e2S1Es=,tag:p2YcYVHguMox+7x+gQguUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
