apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/adguard
  prune: true
  targetNamespace: adguard
  sourceRef:
    kind: GitRepository
    name: flux-system