apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ddns-updater
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/architecture/ddns-updater
  prune: true
  targetNamespace: ddns-updater
  sourceRef:
    kind: GitRepository
    name: flux-system