apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: flux/external-dns  # Make sure this matches your Git repo folder structure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
