apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: overseerr
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/overseerr
  prune: true
  targetNamespace: overseerr
  sourceRef:
    kind: GitRepository
    name: flux-system  
