apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/plex
  prune: true
  targetNamespace: plex
  sourceRef:
    kind: GitRepository
    name: flux-system  
