apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/postgres
  prune: true
  targetNamespace: postgres
  sourceRef:
    kind: GitRepository
    name: flux-system  
  decryption:
    provider: sops
    secretRef:
      name: sops-age