apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/prowlarr
  prune: true
  targetNamespace: prowlarr
  sourceRef:
    kind: GitRepository
    name: flux-system