apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/radarr
  prune: true
  targetNamespace: radarr
  sourceRef:
    kind: GitRepository
    name: flux-system