apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 24h
  path: ./flux/apps/sonarr
  prune: true
  targetNamespace: sonarr
  sourceRef:
    kind: GitRepository
    name: flux-system  