apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 24h
  path: ./architecture/flux-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system