apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: media

spec:
  storageClassName: ""
  volumeName: immich-pv

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Gi