apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:or6T1Yg7SDaDrSSF,iv:e0iV6YipTa0RmvIHG6iAtEtZzSKUuSlq94gRxnstxKc=,tag:Xo1R0/L8NYrCwsOcn9FWHg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:kZbQ4bRn,iv:8gHA5SopamxWU0/SC8MU7Q/FrvW9EHS06PwgTmuz2OU=,tag:1go5Ldv3wlyGbR8pdvISVw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:17CUuVVi,iv:dQQYUjQlgXcztWF37HdGSrXNsDoe4QKtrENbQQc6YNo=,tag:dMbEImUFfStzclzmbfXHdg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:LfOcpCzMIdSx7PRgCoUnZ+Dsc/73UQ==,iv:NXsHHSVAPgT8+P94vXIHD5fIFRKyg/QUmQONVFUb6iE=,tag:zvm3c42ZJiJ/E1JjhqbnAw==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTXJRU3NQUnJZMUtacVV6
            YVh6SVRPYU8zaHVjV2pGSjJIWVN3ZnJDQm40Cnp4NjVkS01zaFhsUlNBZUVobm45
            bWhpRU85b2VnYXdOTUNUYWtGNCtSRnMKLS0tIE02OVpSajVlZndadjlDdmpSYWlu
            d200UEhBN3Z5Uk11WDZlZmVGQThYNUEKnIWGEA0oiwLzTAK99C5cVBBygS970bx5
            0evjf+vG2Rd4RIs24lYzbmGwZFRI8E4KEoc5p0l/UiaeLSlTx+7csQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T02:22:58Z"
    mac: ENC[AES256_GCM,data:twriUAmhMFj3ovEP224t+naq0pXFgK2CHO8Y+Zi1ePO0caP6/hV0EL2qhI4d/tQEWMYTPJRBRLqJtrZLQFhTR1ykdkpcAa6947W9MWlnf4VhhcsJzqqOIEeDTNaGnWxUoXCDn3OhFeL9V260Nz2/4qMHj16caxet6Is/L3DuqiU=,iv:4H97kzSso9EXGjbAlO7irJUJHksVp8dCgvmuydlxDG8=,tag:qL/UtYk29J+HM4ufa06nyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
