apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:4FSHOAA4wQ3Cv4+k,iv:KlN6HtJKqK7uRQxJJEFK/23PZLAF3VdrHlcT+A+CIKQ=,tag:CLUrFhgiGhl2byHQIQLiyA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:e9NnbWy5,iv:Cd1qWZMQ+MX11/UzOUUlPyKZadoJnwCc5n5UJqGe0Kk=,tag:Dp/p9zfDeYxo1sxZ4fWXOw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:hYGY86dy,iv:iPt1wVy1eDDRd0Fa+IQio6ARR3fWIb67EY8j4TgsJqk=,tag:GlgGNlLKkPWyH0Sztr+tEA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ln2IX9cvJ4XLa0rOTkJ+YRmZC06gQw==,iv:wGEzgAwEOVEMvs4iW2gaSBvwKdH7xGKU5zLBooTr8jY=,tag:oNW6jcGd54zQD/QNIzjj3w==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMmlYUi9oRHhyc3M4NmFM
            Zms5VFQ3TXNubjhOWXpYcW5McnZyc3I0RXdFClBCcFFtZ3RsTGRMUGltWkRHdmty
            ZmJnT0lhOXNmVWdhU2RleTFTVFpTS3cKLS0tIDZ4WTFVaTYybU1KTlNkcEVPNFlF
            NkphM1dQRitkWldNeFB5elE1QWlKWW8KiyNGvWTZ3KHRF1rm8fBhwR2uGwJKgGBl
            hD2CJc+VMN5vctzY5CarjnW5FJJ+2FymS0F2KEwcShvWDDRt2EqAAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T01:20:13Z"
    mac: ENC[AES256_GCM,data:4U+pca8cv8WivJBq8IVzEPkkM0io7W1C1cWTlHohzBvNLyjRzcBc62hUYaKekoE6z7W3iTmkkzGA0OL/6uc5qGDymOIo+7Y6OH8KbKso044N8hroUouuSREUrRgzGNKokm2lFCMSewwBtNx8RaC41sDLdXy9/ynL98vQOfIyl4c=,iv:UsVgH+cr6ravl3OV20gFXt9CVlHBSt5OugV6jjLyfTU=,tag:FIhyZDX3UE52s1foUA8wtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
