apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/radarr
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/media/movies
    server: 192.168.0.26
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/qbittorrent/downloads
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime