apiVersion: v1
kind: PersistentVolume
metadata:
  name: wizarr-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/wizarr
    server: 192.168.0.26