apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wizarr-config-pvc
  namespace: wizarr
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: wizarr-config-pv
  resources:
    requests:
      storage: 1Gi