apiVersion: v1
kind: Secret
metadata:
    name: ghost-secrets
    namespace: ghost
type: Opaque
stringData:
    database__connection__user: ENC[AES256_GCM,data:PKuxcMg=,iv:IwJAv/aOP5sQf/n0bKG3mZ8knM/WuJ9YhyOrxPiPpwY=,tag:ds4n5c4KRHAuDxuTMNAfUQ==,type:str]
    database__connection__password: ENC[AES256_GCM,data:KT9sGH9Cam4uSZFyd0c=,iv:tK72VUKUlfwMiBCeU1xHmX0ZPu7/6ip9WpXKbv5VeSE=,tag:pZtuBsqzX3Lp9RnvK+4Ing==,type:str]
    mail__options__auth__user: ENC[AES256_GCM,data:VzcLIcIdwCanPhJqAVwpKPv/iY1DufF9,iv:6VgO8LtwD2uALLz3LT7blx7s20BSs6azXWCbakSZrcw=,tag:Jkdap7Ok/vrB45Loyu+qxQ==,type:str]
    mail__options__auth__pass: ENC[AES256_GCM,data:bqrBbVi0JsR+hwQ/,iv:zHl9rr7EZOiDP11MZy3bkw5U06hXLzOMUGVCq+tnQ5E=,tag:4cFJLqb4NewMXZdaoMfL8Q==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSlFheC81emVqOFFyd3hI
            Y0g5S2NKZzlJVENvdHlPcERVWnMxdEdXczFNCjhUbEh1eWQ2c2dQZU1aZUR3Skxa
            cFJvTytaMHA5UWdadjdONFVUbXp2aWcKLS0tIHJEZDNZa3J3ZlRMSi9URmQ1MEEx
            NEc5cmNIc3hhZVlBbktNZTBrV2tVd00K4DtWn8YM8km9yhcVw1Iyc+GcYkkVSo6J
            pzRTDQomSnxobDlQfPsijnmj6+xfWdCsQFMMBjuLFXUiPXEKyyudwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T04:37:41Z"
    mac: ENC[AES256_GCM,data:9imeafLyzYrwq/rQ/kCCpBgz/vkQ8WxmMEyqXbfYPDl/BV+Az8OIYKyG2tTIKLDxyp3hKKTbk5EqsRUMTQ6C2CKYuKzFxp3WM1MQKavXelajVTYdNw9McaU/ce+jfWSM4u0U9La2D6jhuqoxMlrfqvEBuS+dGq0x0Lgz2FQJQl4=,iv:+3/nAdR+8cfBnCEw4f2piVc7M0qlC3R+4NHbiLkBGms=,tag:80SNgBXeJOvtTagiJiAkog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
