apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:pGWSF4t9,iv:+8mgL9zsB0vzNv5FdFEXoVKeVMuUO/F7PHzmwq1MICg=,tag:goyOptFUufv/E/772GI5fQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:FGiBhvJw51ycKe0L,iv:Uij+Ixj90M8g2rMB6L7zkD1bcp+UNxqaCcF8M6QQMdI=,tag:P/TwvBiaPoTWLuFj2hc/zA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydk5OenR0Uy9NRHdGUStz
            U3pPbTJINnllVU9mbVJXWGkxc3R5c1lCaFV3CnQ3aHRFTWpUMFRsY2ZrZnVxdTFh
            bHI1UmU3ck1pNEFGNVdRM2puZUo1SHcKLS0tIFlRS1JrY2dKU3o3QlgyTmhLdmYv
            NWpjSEJadFFWVWxDbm90L3JJL0JmcDQK/B0CY//dORLq+04k+B5lQR0zKxDdY92p
            NLtTl2YNkW0OILoDqW9H9w3u/ThUipSSxl/Mz4+tlfAy/x9U5fmYcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T03:13:42Z"
    mac: ENC[AES256_GCM,data:YwEZvaLrtdThgZ2qGA0MgEZonaDW5Z3fE3I0UBmai8667RTVrcUFMJYfYwTuZSpNk6pu5FP0yIY1oJ1VCFikT+uw76GF8p47ZzoTW9xRSnkru02BIS2W54W8WetCEF5HkAZRLZk6pGxXkrMYpkHqs5gTq/YwAVuKBC9fsiwV/Ao=,iv:0wLqfbBlEJ6az6O9SC0BRK2p4WiuNef/U61koXMi5QY=,tag:OvqL6arKSq4fwwRADlrhgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
