apiVersion: v1
kind: Service
metadata:
  name: flaresolver
  namespace: flaresolver
spec:
  selector:
    app: flaresolver
  ports:
    - protocol: TCP
      port: 8191
      targetPort: 8191
  type: ClusterIP