apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv

spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  capacity:
    storage: 10Gi

  nfs:
    server: 192.168.1.13
    path: /mnt/apps/audiobookshelf

  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-media-pv

spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  capacity:
    storage: 10Gi

  nfs:
    server: 192.168.1.13
    path: /mnt/media/audiobooks

  mountOptions:
    - nfsvers=4.1
    - noatime