apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.1
        args:
          - --provider=cloudflare
          - --cloudflare-proxied
          - --txt-owner-id=external-dns
          - --domain-filter=alarlab.dev
          - --policy=sync
          - --source=ingress
          - --registry=txt
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: CF_API_TOKEN
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: email
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns

