apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: intel-gpu-plugin 
namespace: intel-device-plugins-system
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/intel/intel-device-plugins-for-kubernetes/main/deployments/gpu_plugin/base/intel-gpu-plugin.yaml
patches:
  - target:
      kind: DaemonSet
      name: intel-gpu-plugin
      namespace: intel-device-plugins-system
    path: patch-daemonset.yaml