apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv

spec:
  persistentVolumeReclaimPolicy: Retain

  accessModes:
    - ReadWriteOnce

  capacity:
    storage: 5Gi

  nfs:
    server: 192.168.1.13
    path: /mnt/apps/home-assistant

  mountOptions:
    - nfsvers=4.1
    - noatime