apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: redis
  name: redis-data
spec:
  storageClassName: ""
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  