apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/apps/prowlarr
    server: 192.168.0.26
  mountOptions:
    - nfsvers=4.1
    - noatime  