apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  releaseName: metallb
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.14.0
      sourceRef:
        kind: GitRepository
        name: metallb-repo
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true