apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-pvc
  namespace: arr-stack

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 5Gi

  volumeName: seerr-config-pv

  storageClassName: ""