apiVersion: v1
kind: Secret
metadata:
    name: wizarr-secret
    namespace: arr-stack
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:GKBW/51Q,iv:D1Ryk8ZDfb2a11bpRyqziO2U0t/RWZS9yQOaiNt7vRM=,tag:SIgXZc26TVl3EkUUbSTYcQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uV2s3yG6zbE4Cmtc,iv:zUDPmf57cqyAMCReJ8jaW2ZUPGDjqsOqZchwrG6JBNk=,tag:iDDaajB5M5kbrMkzWP69IA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZk9rS3JzTS94SkNsV2Vr
            bjVaK0ZHSDlyYWxEVzJ6TjdmU3d3dFR0VkRrCm1PRE1tVDMrUW9ZUlFpVVVHSUlF
            cTBkLzRPRUlFb1hYa0lMTWtuSkFZSmsKLS0tIFJQVndMT0dmK3cvQ25CZmdOQmxY
            U1l5YjBQUERDSmxDdEFITFN4MnQzVlkK8ZYiGxD7VKY+BHX8205NN+RxnMqXrgc4
            rGqyIS9aZgqxlgQzmXPxYbYZYJU+/SBQCoUmiWSvJRY/S2dDLnfnow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T23:28:49Z"
    mac: ENC[AES256_GCM,data:/53K17BevjSEQ9W+f3jHbO2V3MBGSoV5EREITo7k+zF1Q47vuw304fZsa6i1nfP+JGJpYPNmxBgqtFPUpgTrPfFYDjKnUKMC1PRUnOIVC91/cxbF1qnBv/oK+/rvgfcEGh04yGTNlbIeKw7BPsTo80adwjDC61F3Avfmv8gmkOA=,iv:LZP3gNqqB60jAglYCIYlDUA42WBS3RyxgKUxPGZh8nQ=,tag:qcWDSZXORMojYcFBSmWs8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
