apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitt-glueton
  namespace: qbitt-glueton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbitt-glueton
  template:
    metadata:
      labels:
        app: qbitt-glueton
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        ports:
        - containerPort: 51820 # WireGuard port
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "NordVPN"  # Change as per your VPN provider
        - name: VPN_TYPE
          value: "wireguard"
        - name: VPN_USERNAME
          value: "your_vpn_username"
        - name: VPN_PASSWORD
          value: "your_vpn_password"
        - name: VPN_COUNTRY
          value: "US"  # Adjust to preferred country
        volumeMounts:
        - name: gluetun-config
          mountPath: /etc/gluetun

      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        ports:
        - containerPort: 8080
        - containerPort: 6881
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: qbittorrent-downloads
          mountPath: /downloads

      volumes:
      - name: gluetun-config
        persistentVolumeClaim:
          claimName: gluetun-pvc
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: qbittorrent-downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads-pvc
