apiVersion: v1
kind: Secret
metadata:
    name: nordvpn-secret
    namespace: utils
type: Opaque
stringData:
    private_key: ENC[AES256_GCM,data:5ceoGRZopwOP8JgL2UGXy3feIeTCs/slWFzmouGvetEBiiv/8nF9VzwMZqE=,iv:1Ec3swdfLOB4rGL6AJy4efaDCgGipgLc+g6slku5MRk=,tag:vc6w2hAAzf0mxeSNZ2RpyQ==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcEl5bzhsNk5EdVptOUk5
            ZkpkWkxKV3ltL0dDdE1uV3NJSUNBZy9YUlF3CnRtdzd1dytCWjlxUkRjL29sR2dw
            VU9rM2JRbnU3aU1IRUpWbFZraUlHZncKLS0tIHg2bytoZGxITjQ2bGQ4cE9zc1hH
            TlhCeE1UR0hWUjlJbDFpUjBFZTAydGcKcTtN5ijEGMULcrXjBvRWRFMI0/syU0Ma
            4yPsCCNeKLur8Z1T4SMW5/fZBgPVXVVehBmkab1afiKMBsiWWS4OOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T01:19:57Z"
    mac: ENC[AES256_GCM,data:R9WlnCXXvMlkxQvW5vtwG5CEMtqWFE6k4aCYgXM3Y0/HByV1cnht3wgrazqKcj5cv45+O/VlRDjhDMvwFS6/iUFt2ccM7QUPd7TjIBWRt8x1TZsGNZ2Mp4nZAdpG6L4j/Bicil4vD4ifScPK8qlOqYP97m7tbg+1WyZOWwssFEg=,iv:Y8qvhhKldjrEFwkOOc/2MXwE7qPb47ITkuwozy7HWQ4=,tag:9ZHhDmP//VQo90SgZC3BKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
