apiVersion: v1
kind: Secret
metadata:
    name: nordvpn-secret
    namespace: utils
type: Opaque
stringData:
    private_key: ENC[AES256_GCM,data:LqoiqtX4CDyrs5tSWdIV/0xG0ZujxyLoti/VmN1rdN1qKC6rLzEbpkt/Aus=,iv:ZuuIi2dYLq2TKUGUgd0efjvEKjRZ4sk/uSdhuC+KoFM=,tag:s8l4PwgdheVdJrHXpQIzCA==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOVlTV21PV1hPSnZkb3M4
            dTNxcFhHZjF2V214QS91UjRSZXkvbWRFakFzCitlQUZXOS9ZdFBxQU14SUpCSE1L
            Y2FlU3ordVZxVlVVS3M0UlhoZW44TVkKLS0tIFZxZy9iM1BhaStQd28xUVAwbUtV
            VTkyM25yZEZYREIvdEltWW4yRUpmYm8KQJqKt/Gevr7OXNkh+m9Oj6Q48HRtPlez
            Ukz8QAT/LWFfNVXNAS/BkRxef6vTczfX1JwdFXibe9SDPgevyY+Jvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T00:20:56Z"
    mac: ENC[AES256_GCM,data:49Kr1Z6wbuK093qm3M/Y78mMc+LTGCmbfDna9S5EnnFnTvx77+Ek2UTQGmU81shi7YK5eW66ojdhVlg87rMvNHGr8TOihrAV2BzJSVEptXjR/T39enQ+EcNP4XbEdJ7SG8jm9B/CzoEmXLU3XoP2QyqTnUENK/rigMAXK4ggCxI=,iv:9YNL5LjjfH7UQ4ZcjsZb9PfHn6diQ9jF279sm5DmpSs=,tag:0D60eOvCt31N1ADQUai8vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
