apiVersion: v1
kind: Namespace
metadata:
  name: wizarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: wizarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizarr
  template:
    metadata:
      labels:
        app: wizarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-02
      containers:
      - name: wizarr
        image: ghcr.io/wizarrrr/wizarr:latest
        ports:
        - containerPort: 5690
          name: web
        env:
        - name: BASE_URL
          value: "https://plex-invite.alarlab.dev"
        - name: TZ
          value: "America/Denver"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /data/database
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wizarr-config-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wizarr-config-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/apps/wizarr
    server: 192.168.0.26
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wizarr-config-pvc
  namespace: wizarr
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: wizarr-config-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wizarr-service
  namespace: wizarr
spec:
  selector:
    app: wizarr
  ports:
  - port: 5690
    targetPort: 5690
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizarr-ingress
  namespace: wizarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex-invite.alarlab.dev
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: "alarlab.dev"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - plex-invite.alarlab.dev
    secretName: wizarr-tls
  rules:
  - host: plex-invite.alarlab.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wizarr-service
            port:
              number: 5690
  - host: wizarr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wizarr-service
            port:
              number: 5690