apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: utils
type: Opaque
stringData:
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:mgTCBf/XJibJeLl5xtJt4bvUkIA=,iv:BqpaeIIUuqPzcAj7W29xhEFB6FqKitQTTASzKUzJdmg=,tag:wzRtz+9v19NYgIpK2nIVlQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:fliDYlSp,iv:wVI4lK56SMcqX/BgdaFE1HOF5CA5lSgr7Af0zSE4B2k=,tag:BTRkaRY0xtHa+FS7CbsWeA==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:l1nAHxJQ4/9jfx0B,iv:G18BEBVzlEYnRmTmZoQivrFP0qywW/iLTP8aPW9MhNY=,tag:/XjVuI+h6qUPfbYECTUZ5w==,type:str]
    HOMEPAGE_VAR_RADARR_APIKEY: ENC[AES256_GCM,data:0WVPABTvt6+WxUAyjMI48u1egTGx1qulSuWvtQYB35k=,iv:KpxyhMFRToezbLiiDOo2vgDXbIL7jNHigeY4FAMm+eY=,tag:VViirGBcvEh4Mi5mkzNFmA==,type:str]
    HOMEPAGE_VAR_SONARR_APIKEY: ENC[AES256_GCM,data:vh4soGbipOdluSJsNDus+Dp4OD6bRZ0t6KUJBT0wNO8=,iv:v3YyLJBIFsyEWIDdiQjPr8AmH+V43nQMNPpXVHJDg9k=,tag:Va6MqHihfunWHGMCDOGc0A==,type:str]
    HOMEPAGE_VAR_PROWLARR_APIKEY: ENC[AES256_GCM,data:kgnbaoh3sXfo4RmBQ2OyjAGF+Kfq7U/Eb7rQh8aP1B4=,iv:klnX6KhwImVxRAINccRVhV86JPMCXJhX7uJlj4IeXtk=,tag:mEHPA86tRJxy9cavAX7U4Q==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:ahDLYTxv,iv:CA38umfSR4zxbci9UBKhNnYEFWfJJSRJx13iwswJSo8=,tag:SoEr75CV/I5qBSfCTqAyUg==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:dnluICvVCPBqXSrU,iv:DGPLQXPjKvPKiEbibOoB2ooAcEMnfUrlGixsMaMGwig=,tag:sqDz40YM1F7JNCGgrESqIA==,type:str]
    HOMEPAGE_VAR_OVERSEERR_APIKEY: ENC[AES256_GCM,data:Km6pV+j69OjZgnJv9x1xA0+FRxj6YrHkga4VebWmyXImwAaN43ziVO7qYYDOwpuRqbTQdKc3GTOlTxEPhMkTDmus330=,iv:TRXQ/GFpCXsP2w7Gi3LcJzfQwBDzMGfhemT2+drIuV0=,tag:LQXE9j9tqCjbI4oNw/9+5A==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUDJ6VXovSXNLa0FoREQr
            bklmaW9NMFMrVlBtaGc5QWpZdnNEaXNHOGl3CmVUT09IOE9leWYzU0VrR2dVNTRB
            OXpaQXVPOGFIdEVwNzNvUjJaaVZYNjgKLS0tIHdZRml4MDJWRC9ybzlNUnQ3dHlM
            RzY2eThVTTM4dVlEMWdlUGdEZGlXRTQK1WNvkHz+hXphzLjWPB+ZQZCHWe9bbAq5
            mgPVFi5qWMkETyE2QcqwpJOfIQFq3lW5rhyzB8nMEsbAIVXDXahReA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T12:59:07Z"
    mac: ENC[AES256_GCM,data:Ur0O9OxRVfo23lX48QZfC4kboylXsFHVho1ofMEtH1d391k6EjVJMIVAfZUT+rHKe6VNE7ZtQPGD+6eYbnG8AA7Fo/WgrmONo7NQQ6iD/En4Tv1UIpydyokRRgfP677HJ3aiIXz8aSp/bfMy5XCOL+y0rH8PU756uRLFJMAwNn4=,iv:ol+GEYIe99OSsOFkVReMl1Zx5U8jzXKz89YkVK7L9hc=,tag:C3IubGsKCYroWAAYeaNq9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
