apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:mQUHjucUrEo8QsFqTHKS+aBEN8o=,iv:CnvECFtlHspQNtDrhBIupPGH70otnsIPfIMadeIEVEo=,tag:ZZRa27fWH+Zno4uBSoN5sA==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:RE1qvb/g,iv:QsscI1lPEuWKwBi7b7Xbj51MYdG9pXFlu1zw0nZ6mng=,tag:hFQnspsiYHExtcP2LXHXFw==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:zUVKOmEEAEG1R0uw,iv:oSpYiq7G7k/mhCC1URvriif3PRY5f6sIrNABQ6Ua5Cg=,tag:RRcNdxniZe/b9v+kRmjang==,type:str]
    HOMEPAGE_VAR_RADARR_APIKEY: ENC[AES256_GCM,data:53mgiBX9J+24hZbGlE64uwAXwTL8+crcgTo0147QPY8=,iv:gXbK0WZwtWvD4HNZAW4No6QNz8vCbsbXFhy54FNhJU8=,tag:MMWFJHieJlR3l/SipGvYBQ==,type:str]
    HOMEPAGE_VAR_SONARR_APIKEY: ENC[AES256_GCM,data:baNyU8fA9BhcTN98J8CaKwTychG+h3UKcN3+/YjQIsI=,iv:GL8wNyAdmRgVuWtKQBCnamAWmERTfLmo7hXUFgdvLkE=,tag:4QJatT98wEv/BDFfD2Wyfw==,type:str]
    HOMEPAGE_VAR_PROWLARR_APIKEY: ENC[AES256_GCM,data:KksONTkS8OsMG/GjKm503ioShz7ZgsJCbU7D075wvFQ=,iv:UMG/CAG4+1UK2to25R3xcwNRsdnNSuT++TZxnsgdyHs=,tag:ve1Q222u6RVEpEBBIgdzew==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:m02564M6,iv:j6NLRRzWXcTH6bBOsedGdPr3marrDKleJM2nVWJwihI=,tag:MRBJIeMKiePa7tU7tsyZBQ==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:hj645Gg624gfl4xv,iv:SsOb/G6MkGmq3EIWoNXx8FA0CwHFdvwEvhT6M85g+wQ=,tag:6YDFUm0y6/mFtDGBYjOpGA==,type:str]
    HOMEPAGE_VAR_OVERSEERR_APIKEY: ENC[AES256_GCM,data:oXJhZpYp/gtstkte+JmSORm5Kgwffm9e4rZnt0fTFqJ7JZUZjvBSXYNsCtzuq5I8Dtgn+TRvQdq7XgzaQlV18+12iIY=,iv:BmN1P6etq5RNyyo60aGRs3d4PyfWsbAu8vQ8mQugGR0=,tag:N9psBU3K2FMxzk1n9yeGtg==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MmtrWlBUdGxIdk1PTHBu
            cUtnR3c1MVZrU0lleU9YalFKb3lOb3cycmdBCllVbmhHV2duY3dDUzhlSmFTZ2Jn
            Um92a2RiQ2N4NllLamFYcmdzeENxSzQKLS0tIDNwZEVQWXJhQkIvY0FnRlhHZk50
            R2pzZXRYaVhMYWR5K1FLT1gvWWtUUWsK+1BaK2RDRrzCmnK+JDkpguu9uhWzkdQL
            8xLSR2HA2BsYryrFPgbVTMLLWtAC8D4upbHjkcBLoQE6651bHGrBlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T13:21:05Z"
    mac: ENC[AES256_GCM,data:18BKo+hlfDYcOKevkqNqJdwg3c3G7bJhS0zbhEEIqRIZYi/GhA0gFzrmC3fQXm6vorXZW0v6BIZzH8Gpr2ELzkUQNLzI8GC1Y5DLQiOVjwQaMdNOTfrBh6vSn3Bt5HQaDXepWp6t5XNI/4smHoA5aaf/62tKDsYgK1vxxNqpd/c=,iv:23p8jrivUO8zczhj/bdZXSQOyF9P8wUMPYqaUVyTRhE=,tag:JCYTdR5xoAbC2Ybw28Z1Lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
