apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
    namespace: utils
type: Opaque
stringData:
    auth-users: ENC[AES256_GCM,data:mxYp/a42jZ+1VQ1rdzhJg7kk1RamvQYRQn+12TatX9270Q4D51hRSH6sMZQaVLb+RHofL8RrSy0uwb6dAS79PU2g6wSfeuK54Q==,iv:EwtXHcw5w4R63Hb7tdbsGnx7ceay1s6f1PEpjfzE/pI=,tag:irLxIf6vX2U5faF7FFb7Zg==,type:str]
sops:
    age:
        - recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ0JlOXFEeVNlaUxDTW1l
            N2wyREI3MGdXN0VJdHA3bFRaaExiMTBmQ0RvCm9DTmNqdE5JSHlFOG5KeWZ6RGsv
            WFA5TXl3dnBuRkpuTk5SZmdWNU1vcDgKLS0tIHZIVVd4SXNhM0FnbHJ1Y2xpSnJT
            Tmg3cWtTRlovRXdKMFVMTW5SS25vN28KVc75/zNNp6lGyE7FzhvOBaLbgXiENOHx
            eZfgueSTmvGKjGBTsMMfnTMxYS2K4sPsThDpieqqpL/VFbyPBmeYnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T12:56:04Z"
    mac: ENC[AES256_GCM,data:NhN2o5uYcMUC+DEiJvMCmPEN4ju4MSSjG3PNA6hQwn4erBeB5twVAKkjzZTW2npZErQFXqg9kj0mJPqGDFkvaE6OsPesrTw0ZxM2W0QSTKt2wfVklylShDtxZoZbzpziEIrIy1CzoyGmo6BV+0ay3oUmCpWtj42mt5nyqLhNSgY=,iv:at3bAYx7IU7yufdU/Wgc5tqrno+Owt4mbDPNu8D+axk=,tag:C1LkeKM9nHmBqGiVKroHmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
