apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:/i2ka3o/1Lw7CzbQ,iv:YMM81bd8LxiQnELaiBMrpOyvS/f2GN6N6YGgfiijSxk=,tag:IM1RQiaqzpgmEdDcH4G1EQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:S1ffU0EG,iv:wnF3wHo9T7hxjd8/QAYoh5+5JCOx6GKWWW4FnjxKhZU=,tag:KwKpAuKxGFSTBzcWHSC7Ug==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:E66/Fmvx,iv:hOH3aJBa/HoKXGpPPgmzBnAy7XQsdommx5qjL1Lj9o8=,tag:BfVrwkCrndwRCK2h9vurRA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:fhMSAhdAey29W92fghSLnL/6GgKm0A==,iv:qQ69IlrdLTL1ik9pj43FZPL4d7KU2FsNs8xLLAhYSaU=,tag:zWmrda7FHhFwo63We1yEMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZWViOTRQS2FJY2pOWGlw
            MXNKb1Juc1JzTEZxUWhIODJ2NytWTzloQTM0CjhOZjI0UmZGYUVubm5EOWZUODBt
            Q2o2QlpZVlRyLzJHVG9YTGROQTd5RlUKLS0tIGlORzFTa01sbEZUSnV2VVlEYldW
            cEVWRkY2L29vcVNLTnp1WXpjMDlrVDAKnxZ2Em2AtdbTN2JrWyhkibggm4wdCDTe
            hCRGmnybgGU9dxsvvKYXCGW33H1dCb7IM9acX1VEqvyiWFQMDmEuCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dg59p5rlp3ck2dnl3vjdruwp6u7362xs8p3rqykzgl83tp09ss8q9wrnqt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T19:09:50Z"
    mac: ENC[AES256_GCM,data:DL1ORzCkuL/qjd1DDdmtQ9zAANl+vg+04j8prNk85zDcIjt+w8d4Os/UIvVR6C+vmFSQwlneHnY1mh0YYgYHvIY1RPlyLDXqSp77zy4+TOQvmBXx6dnfRjTgV/WuGu0+nSUd5LmDv2wKtvDo1yA27UFwrm4DPJCJRMV8mhXYZZ8=,iv:H2Bfc/jdZbtlfuwo5k42LbmD6w8KgJsuGd5JcO0Cr2w=,tag:/lKvUi+cGIVd8Z0oqcXpbg==,type:str]
    version: 3.13.3
